# Generated by Django 4.2.6 on 2023-10-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dpi_pasaporte', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('num_huespedes_adultos', models.IntegerField()),
                ('num_huespedes_ninos', models.IntegerField()),
                ('edades_ninos', models.CharField(max_length=100)),
                ('tarifas', models.FloatField()),
                ('num_desayunos_buffet', models.IntegerField()),
                ('dias_alquiler_auto', models.IntegerField()),
                ('codigo_tarifa_unica', models.CharField(max_length=100)),
                ('metodo_reserva', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.formapago')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.tipocliente')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.habitacion')),
            ],
        ),
    ]
