# Generated by Django 4.2.6 on 2023-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='dias_alquiler_auto',
            new_name='edad_ninos',
        ),
        migrations.RenameField(
            model_name='reservacion',
            old_name='tipo_habitacion',
            new_name='habitacion',
        ),
        migrations.RenameField(
            model_name='reservacion',
            old_name='num_desayunos_buffet',
            new_name='num_desayunos_buffete',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='codigo_tarifa_unica',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='edades_ninos',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='metodo_reserva',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='tarifas',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='codigo_tarifa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='dias_renta_auto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dpi_pasaporte',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Matrimonial', 'Matrimonial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='forma_pago',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='FormaPago',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
    ]
